version: '3.1'
services:
  wp:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wp
    volumes: 
      - wordpress:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_DATABASE: wp
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes: 
  wordpress:
  db:
